from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def create_pdf(
    patient_data,
    probability,
    risk_level,
    bmi,
    bmi_class,
    pulse_pressure,
    map_value,
    bp_class,
):
    """
    Generate a cardiovascular risk assessment PDF.
    """

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    # -------------------------------
    # Title
    # -------------------------------

    elements.append(
        Paragraph(
            "<b><font color='darkblue' size='18'>CardioPredict</font></b>",
            styles["Title"],
        )
    )

    elements.append(
        Paragraph(
            "Cardiovascular Disease Risk Assessment Report",
            styles["Heading2"],
        )
    )

    elements.append(Spacer(1, 20))

    # -------------------------------
    # Patient Information
    # -------------------------------

    elements.append(
        Paragraph("Patient Information", styles["Heading2"])
    )

    patient_table = Table([
        ["Age", f"{patient_data['age']} years"],
        ["Gender", patient_data["gender"]],
        ["Height", f"{patient_data['height']} cm"],
        ["Weight", f"{patient_data['weight']} kg"],
        ["Blood Pressure",
         f"{patient_data['ap_hi']}/{patient_data['ap_lo']} mmHg"],
    ])

    patient_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))

    elements.append(patient_table)

    elements.append(Spacer(1, 20))

    # -------------------------------
    # Clinical Measurements
    # -------------------------------

    elements.append(
        Paragraph("Clinical Measurements", styles["Heading2"])
    )

    clinical_table = Table([
        ["BMI", f"{bmi:.2f} ({bmi_class})"],
        ["Pulse Pressure", f"{pulse_pressure:.1f} mmHg"],
        ["Mean Arterial Pressure", f"{map_value:.1f} mmHg"],
        ["Blood Pressure Category", bp_class],
    ])

    clinical_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.beige),
    ]))

    elements.append(clinical_table)

    elements.append(Spacer(1, 20))

    # -------------------------------
    # Prediction
    # -------------------------------

    elements.append(
        Paragraph("Prediction", styles["Heading2"])
    )

    prediction_table = Table([
        ["Risk Category", risk_level],
        ["Probability", f"{probability*100:.1f}%"],
    ])

    prediction_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),
    ]))

    elements.append(prediction_table)

    elements.append(Spacer(1, 20))

    # -------------------------------
    # Disclaimer
    # -------------------------------

    elements.append(
        Paragraph("Disclaimer", styles["Heading2"])
    )

    elements.append(
        Paragraph(
            "This report was generated by the CardioPredict Deep Neural "
            "Network and is intended only as a clinical decision-support "
            "tool. It should not replace professional medical judgement.",
            styles["BodyText"],
        )
    )

    doc.build(elements)

    buffer.seek(0)

    return buffer